### PR TITLE
fix: Moving api components

### LINKED ISSUE #509: Refactor JSON RPC Components: Move Models into 'components' Subdirectory
## 📚 Overview

This improvement focuses on refactoring the separation of components models in the `starknet_provider` packages. Currently, components are not clearly separated, leading to potential repetition and maintenance challenges. We propose moving the components models into a dedicated `components` subdirectory within the `model` directory.

## 🔍 Background

In the Starknet JSON RPC API, there is an established notion of [components](https://github.com/starkware-libs/starknet-specs/blob/b4f81445c79b2a8b2b09ff5bb2b7eddca78a32de/api/starknet_api_openrpc.json#L1027) which are reused across methods. Adopting a similar clear separation in our SDK will:

- Enhance maintainability
- Reduce redundancy
- Improve clarity on the code structure

## 🛠️ Requirements

- Move the components models to a new `components` subdirectory within the `model` directory.
- Update the model source code to reflect the new file hierarchy.
- Ensure all relative imports are updated accordingly.
- Verify that all JSON RPC tests pass without issues.

## ✅ Definition of Done

1. Components have been relocated to the `model/components` folder.
2. All references and relative imports in the `model` are updated to match the new structure.
3. JSON RPC tests run green without any errors.

This change is expected to streamline updates and maintenance, aligning the project structure closer to the specification outlined in the Starknet API documentation.

Let's work on this to reduce maintenance issues and improve clarity in our codebase! 🚀

### PR DESCRIPTION
**Pull request by Shashwat-Nautiyal**
Refactored JSON RPC Components inside `/models` by moving Models into 'a separate components' subdirectory. Ensured to update all relative paths.

## Summary by CodeRabbit

- **Chores**
  - Updated internal import and export paths to reflect a new directory structure. No changes to app functionality or public interfaces.
  - Minor cleanup in configuration files (removed a blank line in tool version settings).

### CODE REVIEW

File: packages/starknet_provider/lib/src/model/components/block_hash_and_number.dart
Comment (ptisserand) [inline packages/starknet_provider/lib/src/model/components/block_hash_and_number.dart:1]: According to JSON RPC specification, `block_hash_and_number` is not a component
Components are: 
- [`BLOCK_HASH`](https://github.com/starkware-libs/starknet-specs/blob/b4f81445c79b2a8b2b09ff5bb2b7eddca78a32de/api/starknet_api_openrpc.json#L1471-L1474)
- [`BLOCK_NUMBER`](https://github.com/starkware-libs/starknet-specs/blob/b4f81445c79b2a8b2b09ff5bb2b7eddca78a32de/api/starknet_api_openrpc.json#L1465-L1470)

File: packages/starknet_provider/lib/src/model/components/block_with_receipts.dart [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import 'package:freezed_annotation/freezed_annotation.dart';
 import 'package:starknet/starknet.dart';
-import 'get_transaction_receipt.dart';
+import '../get_transaction_receipt.dart';
```
Comment (ptisserand) [inline packages/starknet_provider/lib/src/model/components/block_with_receipts.dart]: This component should not import the model for `starknet_getTransactionReceipt`

File: packages/starknet_provider/lib/src/model/components/get_block_txn_count.dart
Comment (ptisserand) [inline packages/starknet_provider/lib/src/model/components/get_block_txn_count.dart:1]: According to JSON RPC specification, this is not a component

File: packages/starknet_provider/lib/src/model/components/get_block_with_tx_hashes.dart
Comment (ptisserand) [inline packages/starknet_provider/lib/src/model/components/get_block_with_tx_hashes.dart:1]: According to JSON RPC specification, this is not a component
Components are:
- [`BLOCK_ID`](https://github.com/starkware-libs/starknet-specs/blob/b4f81445c79b2a8b2b09ff5bb2b7eddca78a32de/api/starknet_api_openrpc.json#L1181-L1212)
- [`BLOCK_WITH_TX_HASHES`](https://github.com/starkware-libs/starknet-specs/blob/b4f81445c79b2a8b2b09ff5bb2b7eddca78a32de/api/starknet_api_openrpc.json#L1671-L1695)
- [`PENDING_BLOCK_WITH_TX_HASHES`](https://github.com/starkware-libs/starknet-specs/blob/b4f81445c79b2a8b2b09ff5bb2b7eddca78a32de/api/starknet_api_openrpc.json#L1746-L1759)

File: packages/starknet_provider/lib/src/model/components/get_block_with_txs.dart
Comment (ptisserand) [inline packages/starknet_provider/lib/src/model/components/get_block_with_txs.dart:1]: According to JSON RPC specification, this is not a component

Components are:
- [`BLOCK_ID`](https://github.com/starkware-libs/starknet-specs/blob/b4f81445c79b2a8b2b09ff5bb2b7eddca78a32de/api/starknet_api_openrpc.json#L1181-L1212)
- [`BLOCK_WITH_TXS`](https://github.com/starkware-libs/starknet-specs/blob/b4f81445c79b2a8b2b09ff5bb2b7eddca78a32de/api/starknet_api_openrpc.json#L1696-L1720)
- [`PENDING_BLOCK_WITH_TXS`](https://github.com/starkware-libs/starknet-specs/blob/b4f81445c79b2a8b2b09ff5bb2b7eddca78a32de/api/starknet_api_openrpc.json#L1760-L1773)

**Review by ptisserand — CHANGES_REQUESTED** [review]
Please review the JSON RPC specification to ensure that you are only moving `components` related source code.

File: packages/starknet_provider/lib/src/model/components/get_block_with_tx_hashes.dart
Comment (Shashwat-Nautiyal) [reply packages/starknet_provider/lib/src/model/components/get_block_with_tx_hashes.dart:1]: i was uncertain whether `get_block_with_tx_hashes.gart` was an implementations for [BLOCK_WITH_TX_HASHES](https://github.com/starkware-libs/starknet-specs/blob/b4f81445c79b2a8b2b09ff5bb2b7eddca78a32de/api/starknet_api_openrpc.json#L1671-L1695)

**Comment by ptisserand** [comment]
Hi @Shashwat-Nautiyal could you please update the code to fix the CI.
Even if not all components have been moved, it's a good starting point: thanks a lot.

File: packages/starknet_provider/lib/src/model/components/block_with_receipts.dart [hunk 2]
```diff
@@ -1,6 +1,6 @@
 import 'package:freezed_annotation/freezed_annotation.dart';
 import 'package:starknet/starknet.dart';
-import 'get_transaction_receipt.dart';
+import 'package:starknet_provider/src/model/get_transaction_receipt.dart';
```
Comment (ptisserand) [inline packages/starknet_provider/lib/src/model/components/block_with_receipts.dart:3]: It doesn't make sense for a component to import a model, could you please fix it?

**Review by ptisserand — CHANGES_REQUESTED** [review]

File: packages/starknet_provider/lib/src/model/components/block_with_receipts.dart (hunk 2 above)
Comment (Shashwat-Nautiyal) [reply packages/starknet_provider/lib/src/model/components/block_with_receipts.dart:3]: Somehow without it the tests are running into error. They are failing to find `TxnReceipt` type which is being used in line 11.

Comment (ptisserand) [reply packages/starknet_provider/lib/src/model/components/block_with_receipts.dart:3]: Ok I understand, the point is  that `TxnReceipt` is a component in [JSON RPC spec](https://github.com/starkware-libs/starknet-specs/blob/4233164155b8a279b408b9638c34db2602b5cdc0/api/starknet_api_openrpc.json#L3089)

**Comment by ptisserand** [comment]
Hi @Shashwat-Nautiyal are you still working on it ?

**Comment by Shashwat-Nautiyal** [comment]
> Hi @Shashwat-Nautiyal are you still working on it ?

Sorry, but I didn't understand the last requested change. Without importing `TxnReceipt` type, the test cases were failing.

**Comment by ptisserand** [comment]
> > Hi @Shashwat-Nautiyal are you still working on it ?
> 
> Sorry, but I didn't understand the last requested change. Without importing `TxnReceipt` type, the test cases were failing.

Ok I wasn't clear enough.
I will merge this PR as it and made the modification by myself.
Thanks for your contribution.

**Review by ptisserand — APPROVED** [review]
